import pseudo;
import std;


auto main() -> int {
    try {
        // ================================================================
        // 1. Read SOC input → run upf2upfSO()
        // ================================================================
        UPF soc_in("test/data_io_upf/Si-PD04-FR.upf");
        NCPP pot(soc_in);
        pot.advance.upf2upfSO();

        const auto& meta = pot.meta;
        const auto& nl = pot.nonlocal;
        const auto& wfc = pot.pseudoWfc;

        // ================================================================
        // 2. Read reference output (generated by upf2upfSO.x)
        // ================================================================
        UPF ref("test/data_io_upf/Si-PD04-FR.upf.SO");
        const auto& rh = ref.header();
        const auto& rnl = ref.nonlocal();
        const auto& rwf = ref.wavefunctions();

        // ================================================================
        // 3. Compare structural fields
        // ================================================================
        if (meta.has_so)          throw std::runtime_error("has_so should be false after upf2upfSO");
        if (rh.has_so)            throw std::runtime_error("reference has_so should be false");
        if (meta.l_max != 2)      throw std::runtime_error("l_max should be 2");
        if (rh.l_max != 2)        throw std::runtime_error("reference l_max mismatch");

        if (meta.number_of_proj != 8)
            throw std::runtime_error("nproj should be 8, got " + std::to_string(meta.number_of_proj));
        if (rh.number_of_proj != 8)
            throw std::runtime_error("reference nproj should be 8");
        if (rh.number_of_proj != meta.number_of_proj)
            throw std::runtime_error("nproj mismatch with reference");

        if (meta.number_of_wfc != 2)
            throw std::runtime_error("nwfc should be 2, got " + std::to_string(meta.number_of_wfc));
        if (rh.number_of_wfc != 2)
            throw std::runtime_error("reference nwfc should be 2");

        // ================================================================
        // 4. Compare angular momentum (lll)
        // ================================================================
        // Expected: [0, 0, 1, 1, 2, 2, 10, 20]
        const std::vector<int> expected_lll = {0, 0, 1, 1, 2, 2, 10, 20};
        if (nl.angular_momentum.size() != 8)
            throw std::runtime_error("lll size mismatch");
        if (rnl.lll.size() != 8)
            throw std::runtime_error("reference lll size mismatch");

        for (int i = 0; i < 8; ++i) {
            if (nl.angular_momentum[i] != expected_lll[i])
                throw std::runtime_error("lll[" + std::to_string(i) + "] mismatch: expected " +
                    std::to_string(expected_lll[i]) + ", got " + std::to_string(nl.angular_momentum[i]));
            if (rnl.lll[i] != expected_lll[i])
                throw std::runtime_error("reference lll[" + std::to_string(i) + "] mismatch");
        }

        // ================================================================
        // 5. Compare D diagonal elements
        // ================================================================
        const std::vector<double> expected_D = {
            1.660340673900000E+000,
            1.033868890300000E+001,
            1.156959274939341E+000,
            5.146045028394408E+000,
           -4.854731078574725E+000,
           -9.762231610735784E-001,
            1.608025389768171E-002,
            6.978055187803559E-004
        };

        for (int i = 0; i < 8; ++i) {
            double our_val = nl.B[i, i];
            double ref_val = rnl.dion[i, i];
            double exp_val = expected_D[i];

            double tol = std::max(1e-10, 1e-10 * std::max(1.0, std::abs(exp_val)));
            if (std::abs(our_val - exp_val) > tol)
                throw std::runtime_error("B[" + std::to_string(i) + ", " + std::to_string(i) +
                    "] mismatch: expected " + std::to_string(exp_val) +
                    ", got " + std::to_string(our_val));
            if (std::abs(ref_val - exp_val) > tol)
                throw std::runtime_error("reference B[" + std::to_string(i) + ", " + std::to_string(i) +
                    "] mismatch: expected " + std::to_string(exp_val));
        }

        // ================================================================
        // 6. Compare beta projectors (spot-check at radial mesh points)
        // ================================================================
        // Check a few mesh points across the radial range:
        // i=0 (r=0), i=50 (r≈0.5), i=100 (r≈1.0), i=150 (r≈1.5)
        const std::vector<int> check_indices = {0, 50, 100, 150};
        const double beta_tol = 1e-10;

        for (int ip = 0; ip < 8; ++ip) {
            const auto& our_beta = nl.beta[ip];
            const auto& ref_beta = rnl.beta[ip];
            int compare_len = std::min(static_cast<int>(our_beta.size()),
                                       static_cast<int>(ref_beta.size()));

            for (int idx : check_indices) {
                if (idx >= compare_len) continue;
                double diff = std::abs(our_beta[idx] - ref_beta[idx]);
                double ref_abs = std::abs(ref_beta[idx]);
                double tol = (ref_abs > 1e-10) ? beta_tol * ref_abs : beta_tol;
                if (diff > tol)
                    throw std::runtime_error("beta[" + std::to_string(ip) + "][" +
                        std::to_string(idx) + "]: expected " + std::to_string(ref_beta[idx]) +
                        ", got " + std::to_string(our_beta[idx]) +
                        ", diff=" + std::to_string(diff));
            }
        }

        // ================================================================
        // 7. Compare wavefunction metadata
        // ================================================================
        if (wfc.angular_momentum.size() != 2)
            throw std::runtime_error("lchi size should be 2");
        if (rwf.lchi.size() != 2)
            throw std::runtime_error("reference lchi size should be 2");
        if (wfc.occupation.size() != 2)
            throw std::runtime_error("oc size should be 2");

        const std::vector<int> expected_lchi = {0, 1};
        const std::vector<double> expected_oc = {2.0, 2.0};

        for (int i = 0; i < 2; ++i) {
            if (wfc.angular_momentum[i] != expected_lchi[i])
                throw std::runtime_error("lchi[" + std::to_string(i) + "] mismatch");
            if (rwf.lchi[i] != expected_lchi[i])
                throw std::runtime_error("reference lchi[" + std::to_string(i) + "] mismatch");
            if (std::abs(wfc.occupation[i] - expected_oc[i]) > 1e-10)
                throw std::runtime_error("oc[" + std::to_string(i) + "] mismatch: expected " +
                    std::to_string(expected_oc[i]) + ", got " + std::to_string(wfc.occupation[i]));
        }

        // ================================================================
        // 8. Compare wavefunction values (spot-check)
        // ================================================================
        for (int iw = 0; iw < 2; ++iw) {
            const auto& our_chi = wfc.chi[iw];
            const auto& ref_chi = rwf.chi[iw];
            int compare_len = std::min(static_cast<int>(our_chi.size()),
                                       static_cast<int>(ref_chi.size()));

            for (int idx : check_indices) {
                if (idx >= compare_len) continue;
                double diff = std::abs(our_chi[idx] - ref_chi[idx]);
                double ref_abs = std::abs(ref_chi[idx]);
                double tol = (ref_abs > 1e-10) ? beta_tol * ref_abs : beta_tol;
                if (diff > tol)
                    throw std::runtime_error("chi[" + std::to_string(iw) + "][" +
                        std::to_string(idx) + "]: expected " + std::to_string(ref_chi[idx]) +
                        ", got " + std::to_string(our_chi[idx]));
            }
        }

        // ================================================================
        // 9. Verify D is diagonal (off-diagonals ~ zero)
        // ================================================================
        for (int i = 0; i < 8; ++i) {
            for (int j = 0; j < 8; ++j) {
                if (i == j) continue;
                if (std::abs(nl.B[i, j]) > 1e-15)
                    throw std::runtime_error("B[" + std::to_string(i) + ", " +
                        std::to_string(j) + "] should be 0, got " + std::to_string(nl.B[i, j]));
            }
        }

        // ================================================================
        // 10. Verify jjj/jchi are cleared after upf2upfSO
        // ================================================================
        if (!nl.jjj.empty())
            throw std::runtime_error("jjj should be cleared after upf2upfSO");
        if (!wfc.jchi.empty())
            throw std::runtime_error("jchi should be cleared after upf2upfSO");

        std::println("All upf2upfSO tests passed!");
        return 0;
    } catch (const std::exception& e) {
        std::println(std::cerr, "Test failed: {}", e.what());
        return 1;
    }
}
